import re
from datetime import datetime
from typing import Literal

from pydantic import AliasChoices, BaseModel, Field, field_validator, model_validator

_SLUG_RE = re.compile(r"^[a-z0-9_-]+$")


def validate_template_id(value: str) -> str:
    """The ONE definition of what a template id may be. Returns it, or raises.

    Three readers: `TemplateCreate.id` below, `template_registry.create_draft` /
    `duplicate`, and `template_validation._preview_path`.

    It used to be one — this pydantic validator — which guarded the REST door
    and no other. Chat's `create_template_draft` / `duplicate_template` pass an
    id straight to the registry, the registry did not check, and `Template.id`
    is a bare `Text` primary key with no CHECK constraint, so `../../logs/pwned`
    persisted as a legitimate id and `_preview_path` then interpolated it into
    a real `shutil.copy` destination (SEC-05, 2026-08-19 audit).

    Lives in the schema module because it imports nothing from `app` — a
    service can depend on it without a cycle. The alphabet is deliberately
    narrow: an id names a row AND a filename, so anything that means something
    to a filesystem is excluded rather than escaped.
    """
    if not isinstance(value, str) or not _SLUG_RE.fullmatch(value):
        raise ValueError(
            "template id must be lowercase letters, digits, hyphen, or underscore"
        )
    return value


class TemplateSummary(BaseModel):
    id: str
    display_name: str | None = None
    status: str
    is_default: bool
    origin: str
    engine: str = "latex"
    last_error: str | None = None
    validated_at: datetime | None = None
    # Paired with validated_at so the gallery can mark a thumbnail stale: the
    # preview PDF is only regenerated by validate_template, so a template edited
    # since then still renders its OLD design.
    updated_at: datetime | None = None
    # None = fidelity not yet checked; False = a strict extractor joins words.
    parse_certified: bool | None = None
    # fmt.* variables the source opts into; populated by the router from source.
    supported_fmt_keys: list[str] = []
    # Partial formatting overlay baked into the theme (real column).
    default_formatting: dict | None = None
    # Set = hidden from the gallery and every picker. Carried on the SUMMARY,
    # not just the detail, because the picker needs it: a template archived
    # while still selected must stay visible in that one dropdown, or the
    # selection silently reads as blank.
    archived_at: datetime | None = None
    model_config = {"from_attributes": True}


class TemplateDefaultFormatting(BaseModel):
    formatting: dict | None = None


class TemplateDetail(TemplateSummary):
    source: str
    # Full validation probe report (missing fidelity probes, headers_missing,
    # extra_sections_supported/missing). None until validated. Detail-only:
    # the list payload stays slim.
    parse_report: dict | None = Field(
        default=None,
        validation_alias=AliasChoices("parse_report_json", "parse_report"),
    )


class TemplateCreate(BaseModel):
    id: str
    display_name: str
    # None -> the server's canonical starter source.
    source: str | None = None
    origin: str = "frontend"
    engine: Literal["latex", "typst"] = "latex"

    @model_validator(mode="after")
    def _typst_requires_source(self) -> "TemplateCreate":
        # Phase 1: the canonical starter is LaTeX; it cannot seed a Typst draft.
        if self.engine == "typst" and self.source is None:
            raise ValueError("engine='typst' requires an explicit `source` (.typ text)")
        return self

    @field_validator("id")
    @classmethod
    def _valid_slug(cls, v: str) -> str:
        return validate_template_id(v)


class TemplateUpdate(BaseModel):
    source: str | None = None
    display_name: str | None = None
    engine: Literal["latex", "typst"] | None = None
