"""SQLite baseline.

It replaced a 54-revision Postgres chain (head 85a1bb628e28), which v0.4.0
carried to import compose-era databases and v0.5.0 removed. A fresh database
starts here; runtime seeding (ensure_seed_templates, seeding.run_startup)
covers what the old chain's data migrations did.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871d0425b64c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autofill_field_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('signature_hash', sa.String(length=64), nullable=False),
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('rule_id', sa.Text(), nullable=True),
    sa.Column('outcomes', sa.JSON(), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('session_marks', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature_hash', name='uq_autofill_field_observations_signature_hash')
    )
    op.create_table('base_resumes',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('role_category', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('role_label', sa.Text(), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('tex_path', sa.Text(), nullable=True),
    sa.Column('pdf_rendered_at', sa.DateTime(), nullable=True),
    sa.Column('formatting_json', sa.JSON(), nullable=True),
    sa.Column('template_id', sa.Text(), nullable=True),
    sa.Column('pdf_pages', sa.Integer(), nullable=True),
    sa.Column('render_error', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('last_kb_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('bullet_classifications',
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('override_level', sa.Text(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('content_hash')
    )
    op.create_table('bullet_rewrites',
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('rewrite_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('content_hash')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_ask_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_kind', sa.Text(), nullable=False),
    sa.Column('resume_key', sa.Text(), nullable=False),
    sa.Column('finding_id', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_kind', 'resume_key', 'finding_id', name='uq_health_ask_answer')
    )
    op.create_table('health_gate_waivers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_kind', sa.Text(), nullable=False),
    sa.Column('resume_key', sa.Text(), nullable=False),
    sa.Column('gate_id', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_kind', 'resume_key', 'gate_id', name='uq_health_waiver')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('raw_text_hash', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default='user', nullable=False),
    sa.Column('extracted_json', sa.JSON(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('requisition_id', sa.Text(), nullable=True),
    sa.Column('role_category', sa.Text(), nullable=True),
    sa.Column('level', sa.Text(), nullable=True),
    sa.Column('employment_type', sa.Text(), nullable=True),
    sa.Column('work_mode', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Numeric(), nullable=True),
    sa.Column('salary_max', sa.Numeric(), nullable=True),
    sa.Column('salary_period', sa.Text(), nullable=True),
    sa.Column('salary_currency', sa.Text(), nullable=True),
    sa.Column('salary_source_url', sa.Text(), nullable=True),
    sa.Column('work_authorization', sa.Text(), nullable=True),
    sa.Column('opt_accepted', sa.Text(), nullable=True),
    sa.Column('years_experience_min', sa.Integer(), nullable=True),
    sa.Column('years_experience_max', sa.Integer(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.Column('disqualifying_for_opt', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_text_hash', name='uq_jobs_raw_text_hash')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_role_category_level', ['role_category', 'level'], unique=False)
        batch_op.create_index('ix_jobs_state', ['state'], unique=False)

    op.create_table('kb_entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('org', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='completed', nullable=False),
    sa.Column('detail_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('origin_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kb_profile',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('contact_json', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('skills_json', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('careers_url', sa.Text(), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_lint_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_kind', sa.Text(), nullable=False),
    sa.Column('resume_key', sa.Text(), nullable=False),
    sa.Column('resume_version_number', sa.Integer(), nullable=True),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_lint_reports', schema=None) as batch_op:
        batch_op.create_index('ix_resume_lint_reports_resume', ['resume_kind', 'resume_key'], unique=False)

    op.create_table('resume_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resume_kind', sa.Text(), nullable=False),
    sa.Column('resume_key', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['resume_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_kind', 'resume_key', 'version_number', name='uq_resume_versions_identity')
    )
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.create_index('ix_resume_versions_resume', ['resume_kind', 'resume_key'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('templates',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('engine', sa.Text(), server_default='latex', nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('origin', sa.Text(), server_default='frontend', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('parse_certified', sa.Boolean(), nullable=True),
    sa.Column('parse_report_json', sa.JSON(), nullable=True),
    sa.Column('default_formatting', sa.JSON(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('base_resume', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), server_default='user', nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('customized_json', sa.JSON(), nullable=True),
    sa.Column('formatting_json', sa.JSON(), nullable=True),
    sa.Column('template_id', sa.Text(), nullable=True),
    sa.Column('pdf_pages', sa.Integer(), nullable=True),
    sa.Column('render_error', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('tex_path', sa.Text(), nullable=True),
    sa.Column('artifact_dir', sa.Text(), nullable=True),
    sa.Column('referral_id', sa.Uuid(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('ix_applications_job_id_base_resume', ['job_id', 'base_resume'], unique=False)
        batch_op.create_index('ix_applications_status', ['status'], unique=False)

    op.create_table('chat_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('mime', sa.Text(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_session', ['session_id', 'created_at'], unique=False)

    op.create_table('job_skills',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('skill_name', sa.Text(), nullable=False),
    sa.Column('skill_category', sa.Text(), nullable=False),
    sa.Column('requirement_level', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'skill_name', 'skill_category', 'requirement_level')
    )
    with op.batch_alter_table('job_skills', schema=None) as batch_op:
        batch_op.create_index('ix_job_skills_skill_name', ['skill_name'], unique=False)

    op.create_table('kb_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('mime', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('text_content', sa.Text(), server_default='', nullable=False),
    sa.Column('ingest_status', sa.Text(), server_default='extracted', nullable=False),
    sa.Column('ingest_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['kb_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_documents_entity_id'), ['entity_id'], unique=False)

    op.create_table('application_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('referral_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending_review', nullable=False),
    sa.Column('fit_json', sa.JSON(), nullable=True),
    sa.Column('plan_json', sa.JSON(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('intervention_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('cap_reserved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_proposals', schema=None) as batch_op:
        batch_op.create_index('ix_application_proposals_job_id', ['job_id'], unique=False)
        batch_op.create_index('ix_application_proposals_status', ['status'], unique=False)

    op.create_table('ats_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('composite', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('subscores_json', sa.JSON(), nullable=False),
    sa.Column('skill_table_json', sa.JSON(), nullable=False),
    sa.Column('gaps_json', sa.JSON(), nullable=True),
    sa.Column('config_version', sa.Text(), nullable=False),
    sa.Column('engine_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ats_scores', schema=None) as batch_op:
        batch_op.create_index('ix_ats_scores_application_id', ['application_id'], unique=False)
        batch_op.create_index('ix_ats_scores_job_id_phase', ['job_id', 'phase'], unique=False)
        batch_op.create_index('uq_ats_scores_base_target', ['job_id', 'target_type', 'target_id'], unique=True, sqlite_where=sa.text("phase = 'base'"))

    op.create_table('kb_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default='draft', nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('origin_detail', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('tags_json', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('merge_sources_json', sa.JSON(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['kb_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['kb_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_points_entity_id'), ['entity_id'], unique=False)

    op.create_table('qa_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('evidence_manifest_json', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['application_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_events', schema=None) as batch_op:
        batch_op.create_index('ix_consent_events_proposal_id', ['proposal_id'], unique=False)

    op.create_table('kb_port_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('point_id', sa.Uuid(), nullable=True),
    sa.Column('resume_kind', sa.Text(), server_default='base', nullable=False),
    sa.Column('resume_key', sa.Text(), nullable=False),
    sa.Column('section', sa.Text(), nullable=False),
    sa.Column('ported_text', sa.Text(), server_default='', nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('ported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['kb_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['point_id'], ['kb_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_port_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_port_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_port_log_point_id'), ['point_id'], unique=False)

    op.create_table('tailoring_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('base_resume', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('gaps_json', sa.JSON(), nullable=False),
    sa.Column('resolutions_json', sa.JSON(), nullable=False),
    sa.Column('base_content_hash', sa.Text(), nullable=True),
    sa.Column('jd_extraction_hash', sa.Text(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('base_ats_score_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['base_ats_score_id'], ['ats_scores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tailoring_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_tailoring_sessions_job_id', ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tailoring_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_tailoring_sessions_job_id')

    op.drop_table('tailoring_sessions')
    with op.batch_alter_table('kb_port_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_port_log_point_id'))
        batch_op.drop_index(batch_op.f('ix_kb_port_log_entity_id'))

    op.drop_table('kb_port_log')
    with op.batch_alter_table('consent_events', schema=None) as batch_op:
        batch_op.drop_index('ix_consent_events_proposal_id')

    op.drop_table('consent_events')
    op.drop_table('qa_entries')
    with op.batch_alter_table('kb_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_points_entity_id'))

    op.drop_table('kb_points')
    with op.batch_alter_table('ats_scores', schema=None) as batch_op:
        batch_op.drop_index('uq_ats_scores_base_target', sqlite_where=sa.text("phase = 'base'"))
        batch_op.drop_index('ix_ats_scores_job_id_phase')
        batch_op.drop_index('ix_ats_scores_application_id')

    op.drop_table('ats_scores')
    with op.batch_alter_table('application_proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_application_proposals_status')
        batch_op.drop_index('ix_application_proposals_job_id')

    op.drop_table('application_proposals')
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_documents_entity_id'))

    op.drop_table('kb_documents')
    with op.batch_alter_table('job_skills', schema=None) as batch_op:
        batch_op.drop_index('ix_job_skills_skill_name')

    op.drop_table('job_skills')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_messages_session')

    op.drop_table('chat_messages')
    op.drop_table('chat_attachments')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_status')
        batch_op.drop_index('ix_applications_job_id_base_resume')

    op.drop_table('applications')
    op.drop_table('templates')
    op.drop_table('settings')
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_resume_versions_resume')

    op.drop_table('resume_versions')
    with op.batch_alter_table('resume_lint_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_resume_lint_reports_resume')

    op.drop_table('resume_lint_reports')
    op.drop_table('referrals')
    op.drop_table('kb_profile')
    op.drop_table('kb_entities')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_state')
        batch_op.drop_index('ix_jobs_role_category_level')

    op.drop_table('jobs')
    op.drop_table('health_gate_waivers')
    op.drop_table('health_ask_answers')
    op.drop_table('chat_sessions')
    op.drop_table('bullet_rewrites')
    op.drop_table('bullet_classifications')
    op.drop_table('base_resumes')
    op.drop_table('autofill_field_observations')
    # ### end Alembic commands ###
